title: Blog of Ly525
description: To be a better man

url: https://ly525.github.io/blog
theme: donob

per_page: 7

# menu
menu:
  Archives: /archives/
  About: /about/

default_category: blog

user: ly525
repository: blog

plugins:
  - acyort-rss
  - acyort-archives
  - acyort-paginator

public_dir: public

authors:
  - ly525

timezone: Asia/Shanghai

language:

line_numbers:

order:

token: 9#12c6ebb684b7733eb8c04618d2f6b9fbfbdb681

cache: true

rss: true

archives:
  per_page: 30
